name: 'IAC Parser'
description: 'Parse GitHub repository with Sysdig IAC Parser'
inputs:
  parser:
    description: 'Parser to be used "terraform-state, terraform or cloudformation"'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.parser }}