name: 'IAC Parser'
description: 'Parse GitHub repository with Sysdig IAC Parser'
inputs:
  parser:
    description: 'Parser to be used "terraform-state, terraform or cloudformation"'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Build docker image
      shell: bash
      run: docker build -t sysdiglabs/cloud-iac-scanner -f ./Dockerfile .
    - name: Run IaC Scanner
      shell: bash
      run: docker run sysdiglabs/cloud-iac-scanner:latest ${{github.event.inputs.parser}}
      id: run_iac_scanner
    - name: Print output
      shell: bash
      run: |
        echo ${{steps.run_iac_scanner.outputs.scanner-output}} | while read line; do echo "$line"; done